[2024-09-03T17:40:49.342+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T17:40:49.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.load_Residential_Econ_dim scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T17:40:49.471+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.load_Residential_Econ_dim scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T17:40:49.475+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T17:40:49.537+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_Residential_Econ_dim> on 2024-09-02 00:00:00+00:00
[2024-09-03T17:40:49.561+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T17:40:49.570+0000] {standard_task_runner.py:63} INFO - Started process 159 to run task
[2024-09-03T17:40:49.572+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'load_Residential_Econ_dim', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptf9ctb9y']
[2024-09-03T17:40:49.581+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask load_Residential_Econ_dim
[2024-09-03T17:40:49.821+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.load_Residential_Econ_dim scheduled__2024-09-02T00:00:00+00:00 [running]> on host 9dc6cf14139e
[2024-09-03T17:40:50.075+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='load_Residential_Econ_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T17:40:50.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T17:40:50.113+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T17:40:50.115+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 122, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists='append', index=False, method=insert_on_conflict_nothing)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/processed/Residential_Econ_dim.parquet'
[2024-09-03T17:40:50.150+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=load_Residential_Econ_dim, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T174049, end_date=20240903T174050
[2024-09-03T17:40:50.188+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task load_Residential_Econ_dim ([Errno 2] No such file or directory: '/opt/airflow/data/processed/Residential_Econ_dim.parquet'; 159)
[2024-09-03T17:40:50.245+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T17:40:50.292+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T17:40:50.298+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
