[2024-09-03T17:40:44.776+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T17:40:44.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T17:40:45.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T17:40:45.090+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T17:40:45.255+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-02 00:00:00+00:00
[2024-09-03T17:40:45.299+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T17:40:45.318+0000] {standard_task_runner.py:63} INFO - Started process 151 to run task
[2024-09-03T17:40:45.346+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpnirh8dsx']
[2024-09-03T17:40:45.366+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask transform
[2024-09-03T17:40:45.876+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform scheduled__2024-09-02T00:00:00+00:00 [running]> on host 9dc6cf14139e
[2024-09-03T17:40:46.713+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T17:40:46.725+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T17:40:46.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T17:40:46.820+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 15, in transform_data
    new_batch = pd.read_csv(source_csv, delimiter=',', on_bad_lines='skip', index_col= 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/downloads/CurrentDataBatch.csv'
[2024-09-03T17:40:47.097+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T174044, end_date=20240903T174047
[2024-09-03T17:40:47.324+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task transform ([Errno 2] No such file or directory: '/opt/airflow/data/downloads/CurrentDataBatch.csv'; 151)
[2024-09-03T17:40:47.480+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T17:40:47.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T17:40:47.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
