[2024-09-03T17:59:31.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T17:59:32.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.load_Residential_Econ_dim manual__2024-09-03T17:59:06.450178+00:00 [queued]>
[2024-09-03T17:59:32.183+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.load_Residential_Econ_dim manual__2024-09-03T17:59:06.450178+00:00 [queued]>
[2024-09-03T17:59:32.217+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T17:59:32.359+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_Residential_Econ_dim> on 2024-09-03 17:59:06.450178+00:00
[2024-09-03T17:59:32.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T17:59:32.469+0000] {standard_task_runner.py:63} INFO - Started process 119 to run task
[2024-09-03T17:59:32.486+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'load_Residential_Econ_dim', 'manual__2024-09-03T17:59:06.450178+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmprarn8783']
[2024-09-03T17:59:32.491+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask load_Residential_Econ_dim
[2024-09-03T17:59:33.592+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.load_Residential_Econ_dim manual__2024-09-03T17:59:06.450178+00:00 [running]> on host fdc592a3d39f
[2024-09-03T17:59:34.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='load_Residential_Econ_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T17:59:06.450178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T17:59:06.450178+00:00'
[2024-09-03T17:59:34.534+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T17:59:34.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T17:59:34.658+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 122, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists='append', index=False, method=insert_on_conflict_nothing)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/processed/Residential_Econ_dim.parquet'
[2024-09-03T17:59:34.814+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=load_Residential_Econ_dim, run_id=manual__2024-09-03T17:59:06.450178+00:00, execution_date=20240903T175906, start_date=20240903T175932, end_date=20240903T175934
[2024-09-03T17:59:34.914+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task load_Residential_Econ_dim ([Errno 2] No such file or directory: '/opt/airflow/data/processed/Residential_Econ_dim.parquet'; 119)
[2024-09-03T17:59:35.016+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T17:59:35.063+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
