[2024-09-07T19:53:53.990+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:53:54.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.load_County_dim manual__2024-09-07T19:53:44.526541+00:00 [queued]>
[2024-09-07T19:53:54.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.load_County_dim manual__2024-09-07T19:53:44.526541+00:00 [queued]>
[2024-09-07T19:53:54.078+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:53:54.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_County_dim> on 2024-09-07 19:53:44.526541+00:00
[2024-09-07T19:53:54.493+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:53:54.502+0000] {standard_task_runner.py:63} INFO - Started process 104 to run task
[2024-09-07T19:53:54.492+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'load_County_dim', 'manual__2024-09-07T19:53:44.526541+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpq2yenf6o']
[2024-09-07T19:53:54.505+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_County_dim
[2024-09-07T19:53:54.628+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.load_County_dim manual__2024-09-07T19:53:44.526541+00:00 [running]> on host d49a8c6f87aa
[2024-09-07T19:53:54.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='load_County_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T19:53:44.526541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T19:53:44.526541+00:00'
[2024-09-07T19:53:54.804+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:53:54.855+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:53:54.856+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 127, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists='append', index=False, method=insert_on_conflict_nothing)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/processed/County_dim.parquet'
[2024-09-07T19:53:54.879+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=load_County_dim, run_id=manual__2024-09-07T19:53:44.526541+00:00, execution_date=20240907T195344, start_date=20240907T195354, end_date=20240907T195354
[2024-09-07T19:53:54.900+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task load_County_dim ([Errno 2] No such file or directory: '/opt/airflow/data/processed/County_dim.parquet'; 104)
[2024-09-07T19:53:54.925+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-07T19:53:54.981+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:53:54.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
