[2024-09-03T17:40:30.005+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: solar_adoption_dag.load_TractRecords__fct scheduled__2024-09-02T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
