[2024-09-03T17:40:44.575+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T17:40:44.854+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.load_State_dim manual__2024-09-03T17:40:26.117727+00:00 [queued]>
[2024-09-03T17:40:44.922+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.load_State_dim manual__2024-09-03T17:40:26.117727+00:00 [queued]>
[2024-09-03T17:40:44.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T17:40:45.115+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_State_dim> on 2024-09-03 17:40:26.117727+00:00
[2024-09-03T17:40:45.144+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T17:40:45.149+0000] {standard_task_runner.py:63} INFO - Started process 148 to run task
[2024-09-03T17:40:45.165+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'load_State_dim', 'manual__2024-09-03T17:40:26.117727+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpe5q3nkul']
[2024-09-03T17:40:45.170+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask load_State_dim
[2024-09-03T17:40:45.486+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.load_State_dim manual__2024-09-03T17:40:26.117727+00:00 [running]> on host 9dc6cf14139e
[2024-09-03T17:40:46.311+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='load_State_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T17:40:26.117727+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T17:40:26.117727+00:00'
[2024-09-03T17:40:46.341+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T17:40:46.915+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T17:40:46.932+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 122, in load_data
    pd.read_parquet(table_file).to_sql(table_name, conn, if_exists='append', index=False, method=insert_on_conflict_nothing)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/processed/State_dim.parquet'
[2024-09-03T17:40:47.241+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=load_State_dim, run_id=manual__2024-09-03T17:40:26.117727+00:00, execution_date=20240903T174026, start_date=20240903T174044, end_date=20240903T174047
[2024-09-03T17:40:47.730+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task load_State_dim ([Errno 2] No such file or directory: '/opt/airflow/data/processed/State_dim.parquet'; 148)
[2024-09-03T17:40:48.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T17:40:48.238+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T17:40:48.259+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
