[2024-09-03T18:18:52.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T18:18:52.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:18:46.273339+00:00 [queued]>
[2024-09-03T18:18:52.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:18:46.273339+00:00 [queued]>
[2024-09-03T18:18:52.515+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T18:18:52.544+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-03 18:18:46.273339+00:00
[2024-09-03T18:18:52.555+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T18:18:52.558+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-09-03T18:18:52.558+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'manual__2024-09-03T18:18:46.273339+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpkpvakupn']
[2024-09-03T18:18:52.561+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask transform
[2024-09-03T18:18:52.657+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:18:46.273339+00:00 [running]> on host cd0632279a4b
[2024-09-03T18:18:52.750+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T18:18:46.273339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T18:18:46.273339+00:00'
[2024-09-03T18:18:52.754+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T18:18:52.762+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T18:18:52.763+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 15, in transform_data
    new_batch = pd.read_csv(source_csv, delimiter=',', on_bad_lines='skip', index_col= 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/downloads/CurrentDataBatch.csv'
[2024-09-03T18:18:52.781+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=manual__2024-09-03T18:18:46.273339+00:00, execution_date=20240903T181846, start_date=20240903T181852, end_date=20240903T181852
[2024-09-03T18:18:52.792+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task transform ([Errno 2] No such file or directory: '/opt/airflow/data/downloads/CurrentDataBatch.csv'; 99)
[2024-09-03T18:18:52.814+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T18:18:52.856+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T18:18:52.861+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
