[2024-09-03T18:41:14.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T18:41:14.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:41:08.296565+00:00 [queued]>
[2024-09-03T18:41:14.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:41:08.296565+00:00 [queued]>
[2024-09-03T18:41:14.666+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-03T18:41:14.700+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-03 18:41:08.296565+00:00
[2024-09-03T18:41:14.713+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=118) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T18:41:14.717+0000] {standard_task_runner.py:63} INFO - Started process 120 to run task
[2024-09-03T18:41:14.717+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'manual__2024-09-03T18:41:08.296565+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpoiwyvw8k']
[2024-09-03T18:41:14.719+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask transform
[2024-09-03T18:41:14.842+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform manual__2024-09-03T18:41:08.296565+00:00 [running]> on host cd0632279a4b
[2024-09-03T18:41:15.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T18:41:08.296565+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T18:41:08.296565+00:00'
[2024-09-03T18:41:15.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T18:41:15.331+0000] {logging_mixin.py:188} INFO -           GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
202  9110503101   Connecticut  ...        0.0        0.0
203  9140405401   Connecticut  ...        0.0        0.0
204  9190030300   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-03T18:41:15.336+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-03T18:41:15.342+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-03T18:41:15.344+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-03T18:41:15.351+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_scripts/***_pipeline.py:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TractRecords_fct['state_id'] = clean_batch['s_name'].apply(lambda x: state_dict.get(x))

[2024-09-03T18:41:15.364+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T18:41:15.365+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 94, in transform_data
    Path(target_dir).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/processed'
[2024-09-03T18:41:15.386+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=manual__2024-09-03T18:41:08.296565+00:00, execution_date=20240903T184108, start_date=20240903T184114, end_date=20240903T184115
[2024-09-03T18:41:15.406+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task transform ([Errno 13] Permission denied: '/opt/airflow/data/processed'; 120)
[2024-09-03T18:41:15.423+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T18:41:15.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
