[2024-09-07T19:12:40.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:12:40.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:12:40.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:12:40.364+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:12:40.386+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-06 00:00:00+00:00
[2024-09-07T19:12:40.395+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:12:40.398+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-09-07T19:12:40.397+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptednfs1q']
[2024-09-07T19:12:40.401+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask transform
[2024-09-07T19:12:40.476+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [running]> on host a319a30e0358
[2024-09-07T19:12:40.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-09-07T19:12:40.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:12:40.727+0000] {logging_mixin.py:188} INFO -         GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
0  9110535200   Connecticut  ...        0.0        0.0
1  9110881200   Connecticut  ...     2437.0  2988773.0
2  9110530600   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-07T19:12:40.729+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-07T19:12:40.732+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-07T19:12:40.734+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-07T19:12:40.741+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_scripts/***_pipeline.py:64: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TractRecords_fct['state_id'] = stateIDSeries

[2024-09-07T19:12:40.750+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:12:40.751+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2024-09-06/processed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 95, in transform_data
    Path(target_dir).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/2024-09-06'
[2024-09-07T19:12:40.765+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20240907T191240, end_date=20240907T191240
[2024-09-07T19:12:40.781+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task transform ([Errno 13] Permission denied: '/opt/airflow/data/2024-09-06'; 99)
[2024-09-07T19:12:40.814+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-07T19:12:40.842+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:12:40.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T19:48:09.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:48:09.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:48:09.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:48:09.125+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:48:09.390+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-06 00:00:00+00:00
[2024-09-07T19:48:09.396+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:48:09.397+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-09-07T19:48:09.398+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpkbfxs3ex']
[2024-09-07T19:48:09.401+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask transform
[2024-09-07T19:48:09.455+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [running]> on host 12b5a669b840
[2024-09-07T19:48:09.564+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-09-07T19:48:09.565+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:48:09.652+0000] {logging_mixin.py:188} INFO -             GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
403  9.110416e+09   Connecticut  ...        0.0        0.0
404  9.110462e+09   Connecticut  ...        0.0        0.0
405  9.140406e+09   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-07T19:48:09.654+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-07T19:48:09.656+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-07T19:48:09.658+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-07T19:48:09.663+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_scripts/***_pipeline.py:66: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TractRecords_fct['state_id'] = pd.Series(data=ids,index=ind)

[2024-09-07T19:48:09.669+0000] {logging_mixin.py:188} INFO - break mrk1
[2024-09-07T19:48:09.670+0000] {logging_mixin.py:188} INFO - /opt/***/data/2024-09-06/processed
[2024-09-07T19:48:09.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:48:09.671+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2024-09-06/processed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 99, in transform_data
    Path(target_dir).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/2024-09-06'
[2024-09-07T19:48:09.682+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20240907T194809, end_date=20240907T194809
[2024-09-07T19:48:09.697+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task transform ([Errno 13] Permission denied: '/opt/airflow/data/2024-09-06'; 99)
[2024-09-07T19:48:09.732+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-07T19:48:09.792+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:48:09.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-07T19:53:51.060+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:53:51.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:53:51.176+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-07T19:53:51.178+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:53:51.377+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-06 00:00:00+00:00
[2024-09-07T19:53:51.383+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:53:51.385+0000] {standard_task_runner.py:63} INFO - Started process 92 to run task
[2024-09-07T19:53:51.385+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpwwu5o9ro']
[2024-09-07T19:53:51.388+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask transform
[2024-09-07T19:53:51.442+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform scheduled__2024-09-06T00:00:00+00:00 [running]> on host d49a8c6f87aa
[2024-09-07T19:53:51.540+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-09-07T19:53:51.542+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:53:51.625+0000] {logging_mixin.py:188} INFO -             GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
403  9.110416e+09   Connecticut  ...        0.0        0.0
404  9.110462e+09   Connecticut  ...        0.0        0.0
405  9.140406e+09   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-07T19:53:51.627+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-07T19:53:51.630+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-07T19:53:51.632+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-07T19:53:51.637+0000] {warnings.py:112} WARNING - /opt/***/dags/etl_scripts/***_pipeline.py:66: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TractRecords_fct['state_id'] = pd.Series(data=ids,index=ind)

[2024-09-07T19:53:51.643+0000] {logging_mixin.py:188} INFO - break mrk1
[2024-09-07T19:53:51.644+0000] {logging_mixin.py:188} INFO - /opt/***/data/processed
[2024-09-07T19:53:51.646+0000] {logging_mixin.py:188} INFO - break mrk2
[2024-09-07T19:53:51.916+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-07T19:53:51.916+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:53:51.932+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=solar_adoption_dag, task_id=transform, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20240907T195351, end_date=20240907T195351
[2024-09-07T19:53:52.001+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-07T19:53:52.063+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:53:52.065+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
