[2024-09-07T19:23:39.824+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-07T19:23:39.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:23:35.925864+00:00 [queued]>
[2024-09-07T19:23:40.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:23:35.925864+00:00 [queued]>
[2024-09-07T19:23:40.076+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-07T19:23:40.104+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-09-07 19:23:35.925864+00:00
[2024-09-07T19:23:40.112+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-07T19:23:40.115+0000] {standard_task_runner.py:63} INFO - Started process 271 to run task
[2024-09-07T19:23:40.114+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_adoption_dag', 'transform', 'manual__2024-09-07T19:23:35.925864+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpt2_mvucm']
[2024-09-07T19:23:40.120+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask transform
[2024-09-07T19:23:40.197+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_adoption_dag.transform manual__2024-09-07T19:23:35.925864+00:00 [running]> on host a319a30e0358
[2024-09-07T19:23:40.292+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_adoption_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T19:23:35.925864+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T19:23:35.925864+00:00'
[2024-09-07T19:23:40.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-07T19:23:40.370+0000] {logging_mixin.py:188} INFO -             GEOID     StateName  ... EDU2_kW_ca EDU2_kWh_p
403  9.110416e+09   Connecticut  ...        0.0        0.0
404  9.110462e+09   Connecticut  ...        0.0        0.0
405  9.140406e+09   Connecticut  ...        0.0        0.0

[3 rows x 49 columns]
[2024-09-07T19:23:40.372+0000] {logging_mixin.py:188} INFO - Renamed
[2024-09-07T19:23:40.374+0000] {logging_mixin.py:188} INFO - Keys created
[2024-09-07T19:23:40.376+0000] {logging_mixin.py:188} INFO - keys appended
[2024-09-07T19:23:40.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-07T19:23:40.378+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_scripts/airflow_pipeline.py", line 65, in transform_data
    ids = names.apply(lambda x: state_dict.get(x))
          ^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'apply'
[2024-09-07T19:23:40.395+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=solar_adoption_dag, task_id=transform, run_id=manual__2024-09-07T19:23:35.925864+00:00, execution_date=20240907T192335, start_date=20240907T192339, end_date=20240907T192340
[2024-09-07T19:23:40.410+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task transform ('numpy.ndarray' object has no attribute 'apply'; 271)
[2024-09-07T19:23:40.452+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-07T19:23:40.485+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-07T19:23:40.494+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
